# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title count compare (internal only)
#' @description Given a dataset and a data.frame of comparison patterns,
#' count the number of occurances of each pattern. Internally called by \code{count_levels}.
#' @param dat A \code{data.frame}. All variables must be factors
#' @param x A \code{data.frame} consisting of all possible patterns for matching
#' with \code{dat}.
#' @param hasNA A string. Denotes if \code{dat} has complete data or not.
NULL

count_compare <- function(x, dat, hasNA) {
    .Call('_imputeMulti_count_compare', PACKAGE = 'imputeMulti', x, dat, hasNA)
}

#' @title Calculate the sup of L1 distance between x and y
#' @description sup of L1 distance between x and y
#' @param x A numeric \code{vector}
#' @param y A numeric \code{vector}
#' @return a numeric scalar.
supDistC <- function(x, y) {
    .Call('_imputeMulti_supDistC', PACKAGE = 'imputeMulti', x, y)
}

