# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title count compare (internal only)
#' @description Given a dataset and a data.frame of comparison patterns,
#' count the number of occurances of each pattern. Internally called by \code{count_levels}.
#' @param dat A \code{data.frame}. All variables must be factors
#' @param x A \code{data.frame} consisting of all possible patterns for matching
#' with \code{dat}.
#' @param hasNA A string. Denotes if \code{dat} has complete data or not.
NULL

count_compare <- function(x, dat, hasNA) {
    .Call('_imputeMulti_count_compare', PACKAGE = 'imputeMulti', x, dat, hasNA)
}

#' @title Calculate the sup of L1 distance between x and y
#' @description sup of L1 distance between x and y
#' @param x A numeric \code{vector}
#' @param y A numeric \code{vector}
#' @return a numeric scalar.
supDistC <- function(x, y) {
    .Call('_imputeMulti_supDistC', PACKAGE = 'imputeMulti', x, y)
}

#' @title Compare two integer matrices, allowing missing values
#' @description Compare two two-dimensional arrays (\code{mat_x}, \code{mat_y}), where \code{mat_x}
#' permits missing values. Return a \code{list} of length \code{nrow(mat_x)} such that each list
#' element contains a vector of row indices from \code{mat_y} with row-equivalence of the non
#' missing values.
#' @param mat_x A two dimensional array which may contain missing values
#' @param mat_y A two dimensional array without missing values
#' @return A \code{list} of matches.
xy_compare <- function(mat_x, mat_y) {
    .Call('_imputeMulti_xy_compare', PACKAGE = 'imputeMulti', mat_x, mat_y)
}

